Implement a little library that contains general utilities
eirys/megamimOS pull request #13
Opened 2024-02-15 04:16 UTC by JonathanDUFOUR

This pull request is related to the issue #6. Every requested function has been implemented and tested. The only difference is their name. Here is the list of the actual names for the functions of the library:
- memCmp
- memCpy
- memMov
- memSet
- strCmp
- strCpy
- strLen

2024-02-15 08:44 UTC, nils-mathieu approved these changes
lgtm

2024-02-15 14:48 UTC, eirys requested changes
lots of reverting

2024-02-15 14:48 UTC, eirys commented on lib/Makefile
> -	@echo "Removed $(NAME)."
No

2024-02-15 14:48 UTC, eirys commented on lib/Makefile
> +	@echo "Removed object files, $(NAME), and $(TEST)."
No

2024-02-15 14:48 UTC, eirys commented on lib/Makefile
> +re: clean all
No

2024-02-15 14:48 UTC, eirys commented on lib/Makefile
> +fre: fclean all
No

2024-02-15 14:48 UTC, eirys commented on lib/Makefile
Redo makefile properly

2024-02-15 14:48 UTC, eirys commented on Makefile
revert unwanted changes

2024-02-15 14:48 UTC, eirys commented on lib/include/types.h
using not typedef

2024-02-15 14:48 UTC, eirys commented on lib/src/test/main.cpp
rename to test or sth more explicit

2024-02-15 14:48 UTC, eirys commented on lib/include/types.h
> +#include <unistd.h>
allowed?? and why??

2024-02-15 14:48 UTC, eirys commented on lib/include/types.h
> +typedef size_t usize;
discard and use u32

2024-02-16 00:11 UTC, eirys commented on src/ui/terminal.h
> +    void putString(const char* str) {
?????

2024-02-16 00:14 UTC, eirys reviewed
requires manual merging lol! pls pull

2024-02-16 00:41 UTC, merged